-- Phase 2: registration_entry_slots, per CLAUDE.md Section 3 DDL. Rows are
-- generated by the registration service (one per required starter), all
-- starting payment_status = 'unpaid'. No Stripe/checkout code yet — that's
-- Phase 3.

create table registration_entry_slots (
  entry_slot_id uuid primary key default gen_random_uuid(),
  registration_id uuid not null references tournament_registrations(registration_id) on delete cascade,
  slot_number int not null,
  assigned_starter_user_id uuid references users(user_id),
  entry_fee_amount_cents int not null,
  currency text not null default 'usd',
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid','checkout_pending','paid','payment_failed','refunded','partially_refunded','chargeback_pending','charged_back','waived','admin_review')),
  checkout_lock_status text not null default 'available'
    check (checkout_lock_status in ('available','locked_for_checkout','paid','expired','released')),
  checkout_lock_expires_at timestamptz,
  payer_user_id uuid references users(user_id),
  payment_id uuid,
  payout_entitlement_user_id uuid references users(user_id),
  entitlement_status text not null default 'pending'
    check (entitlement_status in ('pending','active','locked','payout_pending','paid_out','transferred','cancelled','forfeited','admin_review')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (registration_id, slot_number)
);

alter table registration_entry_slots enable row level security;

create policy "registration_entry_slots read own or own team or payer or admin" on registration_entry_slots
  for select using (
    assigned_starter_user_id = public.current_app_user_id()
    or payer_user_id = public.current_app_user_id()
    or exists (
      select 1 from public.tournament_registrations r
      join public.teams t on t.team_id = r.team_id
      where r.registration_id = registration_entry_slots.registration_id
        and t.captain_user_id = public.current_app_user_id()
    )
    or public.is_admin()
  );

grant select on registration_entry_slots to anon, authenticated;
grant select, insert, update, delete on registration_entry_slots to service_role;
